[package]
name = "nan_deck_parser"
version = "0.1.3"
edition = "2021"
authors = ["Artemiy Boykov", "<arhimondus@gmail.com>"]
repository = "https://github.com/Arhimondus/nan_deck_parser"

[dependencies]
